package aa

// Model represents a single AI model entry from artificialanalysis.ai.
type Model struct {
	ActiveParameters                    *int64                            `json:"activeParameters"`
	AgenticIndex                        *float64                          `json:"agenticIndex"`
	ApexAgents                          *float64                          `json:"apexAgents"`
	CacheHitDiscountPercent             *float64                          `json:"cacheHitDiscountPercent"`
	CacheHitPrice                       *float64                          `json:"cacheHitPrice"`
	CodingIndex                         *float64                          `json:"codingIndex"`
	CommercialAllowed                   *bool                             `json:"commercialAllowed"`
	ContextWindowTokens                 *int64                            `json:"contextWindowTokens"`
	Critpt                              *float64                          `json:"critpt"`
	Deprecated                          bool                              `json:"deprecated"`
	EvalTokenCounts                     map[string]EvalTokenCount         `json:"evalTokenCounts"`
	GdpvalBreakdown                     *GdpvalBreakdown                  `json:"gdpvalBreakdown"`
	GdpvalNormalized                    *float64                          `json:"gdpvalNormalized"`
	Gpqa                                *float64                          `json:"gpqa"`
	Hle                                 *float64                          `json:"hle"`
	HuggingfaceURL                      *string                           `json:"huggingfaceUrl"`
	ID                                  string                            `json:"id"`
	Ifbench                             *float64                          `json:"ifbench"`
	InputModalityImage                  bool                              `json:"inputModalityImage"`
	InputModalitySpeech                 bool                              `json:"inputModalitySpeech"`
	InputModalityText                   bool                              `json:"inputModalityText"`
	InputModalityVideo                  bool                              `json:"inputModalityVideo"`
	IntelligenceIndex                   *float64                          `json:"intelligenceIndex"`
	IntelligenceIndexCostAnswer         *float64                          `json:"intelligenceIndexCostAnswer"`
	IntelligenceIndexCostInput          *float64                          `json:"intelligenceIndexCostInput"`
	IntelligenceIndexCostOutput         *float64                          `json:"intelligenceIndexCostOutput"`
	IntelligenceIndexCostReasoning      *float64                          `json:"intelligenceIndexCostReasoning"`
	IntelligenceIndexCostTotal          *float64                          `json:"intelligenceIndexCostTotal"`
	IntelligenceIndexIsEstimated        bool                              `json:"intelligenceIndexIsEstimated"`
	IntelligenceIndexTokenCounts        *EvalTokenCount                   `json:"intelligenceIndexTokenCounts"`
	IsOpenWeights                       bool                              `json:"isOpenWeights"`
	ItbenchSre                          *float64                          `json:"itbenchSre"`
	Lcr                                 *float64                          `json:"lcr"`
	LicenseName                         *string                           `json:"licenseName"`
	LicenseURL                          *string                           `json:"licenseUrl"`
	MedianEndToEndResponseTimeSeconds   *float64                          `json:"medianEndToEndResponseTimeSeconds"`
	MedianOutputTokensPerSecond         *float64                          `json:"medianOutputTokensPerSecond"`
	MedianReasoningTimeSeconds          *float64                          `json:"medianReasoningTimeSeconds"`
	MedianTimeToFirstAnswerTokenSeconds *float64                          `json:"medianTimeToFirstAnswerTokenSeconds"`
	MedianTimeToFirstTokenSeconds       *float64                          `json:"medianTimeToFirstTokenSeconds"`
	MmmuPro                             *float64                          `json:"mmmuPro"`
	ModelCreatorColor                   string                            `json:"modelCreatorColor"`
	ModelCreatorCountry                 string                            `json:"modelCreatorCountry"`
	ModelCreatorID                      string                            `json:"modelCreatorId"`
	ModelCreatorLogo                    string                            `json:"modelCreatorLogo"`
	ModelCreatorName                    string                            `json:"modelCreatorName"`
	ModelCreatorSlug                    string                            `json:"modelCreatorSlug"`
	MultilingualBreakdown               *MultilingualBreakdown            `json:"multilingualBreakdown"`
	Name                                string                            `json:"name"`
	Omniscience                         *float64                          `json:"omniscience"`
	OmniscienceAccuracy                 *float64                          `json:"omniscienceAccuracy"`
	OmniscienceBreakdown                map[string]OmniscienceDomainScore `json:"omniscienceBreakdown"`
	OmniscienceNonHallucination         *float64                          `json:"omniscienceNonHallucination"`
	OpennessBreakdown                   *OpennessBreakdown                `json:"opennessBreakdown"`
	OpenrouterAPIID                     *string                           `json:"openrouterApiId"`
	OutputModalityImage                 bool                              `json:"outputModalityImage"`
	OutputModalitySpeech                bool                              `json:"outputModalitySpeech"`
	OutputModalityText                  bool                              `json:"outputModalityText"`
	OutputModalityVideo                 bool                              `json:"outputModalityVideo"`
	Percentile05OutputTokensPerSecond   *float64                          `json:"percentile05OutputTokensPerSecond"`
	Percentile05TimeToFirstTokenSeconds *float64                          `json:"percentile05TimeToFirstTokenSeconds"`
	Percentile95OutputTokensPerSecond   *float64                          `json:"percentile95OutputTokensPerSecond"`
	Percentile95TimeToFirstTokenSeconds *float64                          `json:"percentile95TimeToFirstTokenSeconds"`
	Price1MBlended0To100To1             *float64                          `json:"price1mBlended0To100To1"`
	Price1MBlended0To1To1               *float64                          `json:"price1mBlended0To1To1"`
	Price1MBlended0To3To1               *float64                          `json:"price1mBlended0To3To1"`
	Price1MBlended100To1To1             *float64                          `json:"price1mBlended100To1To1"`
	Price1MBlended7To2To1               *float64                          `json:"price1mBlended7To2To1"`
	Price1MInputTokens                  *float64                          `json:"price1mInputTokens"`
	Price1MOutputTokens                 *float64                          `json:"price1mOutputTokens"`
	PriceClass                          *string                           `json:"priceClass"`
	Quartile25OutputTokensPerSecond     *float64                          `json:"quartile25OutputTokensPerSecond"`
	Quartile25TimeToFirstTokenSeconds   *float64                          `json:"quartile25TimeToFirstTokenSeconds"`
	Quartile75OutputTokensPerSecond     *float64                          `json:"quartile75OutputTokensPerSecond"`
	Quartile75TimeToFirstTokenSeconds   *float64                          `json:"quartile75TimeToFirstTokenSeconds"`
	ReasoningModel                      bool                              `json:"reasoningModel"`
	ReleaseDate                         *string                           `json:"releaseDate"`
	Scicode                             *float64                          `json:"scicode"`
	ShortName                           string                            `json:"shortName"`
	SizeClass                           *string                           `json:"sizeClass"`
	Slug                                string                            `json:"slug"`
	Tau2                                *float64                          `json:"tau2"`
	TerminalbenchHard                   *float64                          `json:"terminalbenchHard"`
	TotalParameters                     *int64                            `json:"totalParameters"`
	TrainingTokensTrillions             *float64                          `json:"trainingTokensTrillions"`
}
