// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type ModelSnapshot struct {
	ID                int64           `json:"id"`
	ScrapeID          int64           `json:"scrape_id"`
	ModelID           string          `json:"model_id"`
	Slug              string          `json:"slug"`
	Name              string          `json:"name"`
	CreatorName       string          `json:"creator_name"`
	IntelligenceIndex sql.NullFloat64 `json:"intelligence_index"`
	CodingIndex       sql.NullFloat64 `json:"coding_index"`
	PriceInput        sql.NullFloat64 `json:"price_input"`
	PriceOutput       sql.NullFloat64 `json:"price_output"`
	Data              string          `json:"data"`
}

type Scrape struct {
	ID         int64     `json:"id"`
	ScrapedAt  time.Time `json:"scraped_at"`
	ModelCount int64     `json:"model_count"`
}
