// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getLatestScrape = `-- name: GetLatestScrape :one
SELECT id, scraped_at, model_count FROM scrapes ORDER BY scraped_at DESC LIMIT 1
`

func (q *Queries) GetLatestScrape(ctx context.Context) (Scrape, error) {
	row := q.db.QueryRowContext(ctx, getLatestScrape)
	var i Scrape
	err := row.Scan(&i.ID, &i.ScrapedAt, &i.ModelCount)
	return i, err
}

const getModelBySlug = `-- name: GetModelBySlug :one
SELECT ms.id, ms.scrape_id, ms.model_id, ms.slug, ms.name, ms.creator_name, ms.intelligence_index, ms.coding_index, ms.price_input, ms.price_output, ms.data FROM model_snapshots ms
WHERE ms.slug = ?
  AND ms.scrape_id = (SELECT id FROM scrapes ORDER BY scraped_at DESC LIMIT 1)
`

func (q *Queries) GetModelBySlug(ctx context.Context, slug string) (ModelSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getModelBySlug, slug)
	var i ModelSnapshot
	err := row.Scan(
		&i.ID,
		&i.ScrapeID,
		&i.ModelID,
		&i.Slug,
		&i.Name,
		&i.CreatorName,
		&i.IntelligenceIndex,
		&i.CodingIndex,
		&i.PriceInput,
		&i.PriceOutput,
		&i.Data,
	)
	return i, err
}

const getModelBySlugAndScrapeID = `-- name: GetModelBySlugAndScrapeID :one
SELECT id, scrape_id, model_id, slug, name, creator_name, intelligence_index, coding_index, price_input, price_output, data FROM model_snapshots WHERE scrape_id = ? AND slug = ?
`

type GetModelBySlugAndScrapeIDParams struct {
	ScrapeID int64  `json:"scrape_id"`
	Slug     string `json:"slug"`
}

func (q *Queries) GetModelBySlugAndScrapeID(ctx context.Context, arg GetModelBySlugAndScrapeIDParams) (ModelSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getModelBySlugAndScrapeID, arg.ScrapeID, arg.Slug)
	var i ModelSnapshot
	err := row.Scan(
		&i.ID,
		&i.ScrapeID,
		&i.ModelID,
		&i.Slug,
		&i.Name,
		&i.CreatorName,
		&i.IntelligenceIndex,
		&i.CodingIndex,
		&i.PriceInput,
		&i.PriceOutput,
		&i.Data,
	)
	return i, err
}

const getScrapeClosestTo = `-- name: GetScrapeClosestTo :one
SELECT id, scraped_at, model_count FROM scrapes WHERE scraped_at <= ? ORDER BY scraped_at DESC LIMIT 1
`

func (q *Queries) GetScrapeClosestTo(ctx context.Context, scrapedAt time.Time) (Scrape, error) {
	row := q.db.QueryRowContext(ctx, getScrapeClosestTo, scrapedAt)
	var i Scrape
	err := row.Scan(&i.ID, &i.ScrapedAt, &i.ModelCount)
	return i, err
}

const insertModelSnapshot = `-- name: InsertModelSnapshot :exec
INSERT INTO model_snapshots
    (scrape_id, model_id, slug, name, creator_name,
     intelligence_index, coding_index, price_input, price_output, data)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertModelSnapshotParams struct {
	ScrapeID          int64           `json:"scrape_id"`
	ModelID           string          `json:"model_id"`
	Slug              string          `json:"slug"`
	Name              string          `json:"name"`
	CreatorName       string          `json:"creator_name"`
	IntelligenceIndex sql.NullFloat64 `json:"intelligence_index"`
	CodingIndex       sql.NullFloat64 `json:"coding_index"`
	PriceInput        sql.NullFloat64 `json:"price_input"`
	PriceOutput       sql.NullFloat64 `json:"price_output"`
	Data              string          `json:"data"`
}

func (q *Queries) InsertModelSnapshot(ctx context.Context, arg InsertModelSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertModelSnapshot,
		arg.ScrapeID,
		arg.ModelID,
		arg.Slug,
		arg.Name,
		arg.CreatorName,
		arg.IntelligenceIndex,
		arg.CodingIndex,
		arg.PriceInput,
		arg.PriceOutput,
		arg.Data,
	)
	return err
}

const insertScrape = `-- name: InsertScrape :one
INSERT INTO scrapes (scraped_at, model_count) VALUES (?, ?) RETURNING id, scraped_at, model_count
`

type InsertScrapeParams struct {
	ScrapedAt  time.Time `json:"scraped_at"`
	ModelCount int64     `json:"model_count"`
}

func (q *Queries) InsertScrape(ctx context.Context, arg InsertScrapeParams) (Scrape, error) {
	row := q.db.QueryRowContext(ctx, insertScrape, arg.ScrapedAt, arg.ModelCount)
	var i Scrape
	err := row.Scan(&i.ID, &i.ScrapedAt, &i.ModelCount)
	return i, err
}

const listModelsByLatestScrape = `-- name: ListModelsByLatestScrape :many
SELECT ms.id, ms.scrape_id, ms.model_id, ms.slug, ms.name, ms.creator_name, ms.intelligence_index, ms.coding_index, ms.price_input, ms.price_output, ms.data FROM model_snapshots ms
WHERE ms.scrape_id = (SELECT id FROM scrapes ORDER BY scraped_at DESC LIMIT 1)
ORDER BY ms.intelligence_index DESC
`

func (q *Queries) ListModelsByLatestScrape(ctx context.Context) ([]ModelSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listModelsByLatestScrape)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelSnapshot
	for rows.Next() {
		var i ModelSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ScrapeID,
			&i.ModelID,
			&i.Slug,
			&i.Name,
			&i.CreatorName,
			&i.IntelligenceIndex,
			&i.CodingIndex,
			&i.PriceInput,
			&i.PriceOutput,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsByScrapeID = `-- name: ListModelsByScrapeID :many
SELECT id, scrape_id, model_id, slug, name, creator_name, intelligence_index, coding_index, price_input, price_output, data FROM model_snapshots WHERE scrape_id = ? ORDER BY intelligence_index DESC
`

func (q *Queries) ListModelsByScrapeID(ctx context.Context, scrapeID int64) ([]ModelSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listModelsByScrapeID, scrapeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelSnapshot
	for rows.Next() {
		var i ModelSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ScrapeID,
			&i.ModelID,
			&i.Slug,
			&i.Name,
			&i.CreatorName,
			&i.IntelligenceIndex,
			&i.CodingIndex,
			&i.PriceInput,
			&i.PriceOutput,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScrapes = `-- name: ListScrapes :many
SELECT id, scraped_at, model_count FROM scrapes ORDER BY scraped_at DESC
`

func (q *Queries) ListScrapes(ctx context.Context) ([]Scrape, error) {
	rows, err := q.db.QueryContext(ctx, listScrapes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scrape
	for rows.Next() {
		var i Scrape
		if err := rows.Scan(&i.ID, &i.ScrapedAt, &i.ModelCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
